### PR TITLE
[Do Not Merge] Generate models of orthologous protein:ligand complexes in fragalysis format

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description
Provide a brief description of the PR's purpose here.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] TODO 1

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by mikemhenry** [comment]
We only have a few merge conflicts + some debugging stuff + new scripts.

I would like to get things merged before we split things up, so that we don't have to re-do that effort after we merge this branch in (or have to do it twice)

**Comment by dotsdl** [comment]
Thank you everyone! For clarification, by "hallucinate Fragalysis", do we mean producing docked targets+ligands in Fragalysis-format from target structures obtained elsewhere?

**Comment by jchodera** [comment]
> Thank you everyone! For clarification, by "hallucinate Fragalysis", do we mean producing docked targets+ligands in Fragalysis-format from target structures obtained elsewhere?

I've changed the name of the PR to something hopefully more informative:
"Generate models of orthologous protein:ligand complexes in fragalysis format"

**Comment by ijpulidos** [comment]
Closing this PR in order to avoid unintended side effects when removing the data from git and github history.

**Pull request closed without merging**
